### PR TITLE
Create SongRepositoryTests, singerList.html

### PR DESCRIPTION
**Pull request by WhatIsTheDifference**
Create SongRepositoryTests, singerList.html

### CODE REVIEW

**Comment by atomfrede** [comment]
@MksmChldny Nice work (-> more unit tests -> increased coverage, which is fine), but I have a few troubles with this PR (some of them are mostly my fault):
- You've commited all eclipse specific files and folders (I've not added them to the `.gitignore`), but IDE specific files and folders shoould not be under version control
- ~~Which OS and what git client/tool are you using? _Every_ file is reformatted (I guess tabs VS spaces and lineendings), which makes tracking a specific change impossible.~~
- Some general guideline for git commit messages: First line: Whats the intention of this commit <BLANK LINE> and then some further description (if required).

So maybe you can update your PR to exclude eclipse specific files and have a look at your git/ide settings regarding formatting and line endings, so I know what has happend.

_EDIT_ Sorry, I didn't see the file path. You have a complete copy of the project in `/bin` was this folder created by eclipse or netbeans?

**Comment by WhatIsTheDifference** [comment]
@atomfrede Thank you for your quick feedback.
My first try was the pull request method in the browser on github.com. I have pushed all files, including the unneeded eclipse specific files.
The folder “/bin” was created by eclipse. In the new PR I have edited the .gitignore-file and I hope that the new PR is more appealing than the first.

**Comment by atomfrede** [comment]
@MksmChldny Do you have already pushed your latest changes to your repository? Then this PR should be updated automatically.

**Comment by WhatIsTheDifference** [comment]
yes, I have pushed over eclipse -> project -> team -> commit -> commit and push

**Comment by atomfrede** [comment]
Strange, I looks like it was not pushed correctly. See your repository, the latest commit is from yesterday.

**Comment by WhatIsTheDifference** [comment]
ok. it seems like there is a problem
"Failed pushing to turbo-adventure - origin"
"https://github.com/atomfrede/turbo-adventure.git: git-receive-pack not permitted"

**Comment by atomfrede** [comment]
Ok, you've cloned _my_ repository (you don't have write access to it). You should clone _your_ fork:
https://github.com/MksmChldny/turbo-adventure

**Comment by WhatIsTheDifference** [comment]
That makes sense.
Thank you for help!

**Comment by atomfrede** [comment]
@MksmChldny I've merged your PR. You should update your repository with the upstream changes with `git fetch upstream` and `git merge upstream/master`.

This fetches all changes from upstream and merges `upstream/master` into your local branch. **But  beware**: You might reimport your project into eclipse as I've removed all eclipse specific files.

**Comment by WhatIsTheDifference** [comment]
@atomfrede Ok, if I update my repository with the upstream changes with “git fetch ….” what is with the changes I have created between my last PR and the planned upstream. They will be lost?

**Comment by atomfrede** [comment]
Just commit your local changes. The upstream changes will be merged (you should have no conflicts). So in short nothing will be lost.

**Pull request merged**
